name: My First workflow
on: [push, workflow_dispatch]
jobs:
  my-firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: List all files
        run: ls -a
      - name: Print working directory
        run: pwd
      - name: Checkout Repo
        uses: actions/checkout@v6
